import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";
export function makeXlsx(fixtures,timezone){
 const rows=[]; for(const f of fixtures){const time=new Intl.DateTimeFormat("en-GB",{timeZone:timezone,dateStyle:"short",timeStyle:"short",hour12:false}).format(new Date(f.startMs)); for(const m of f.markets) for(const o of m.outcomes) rows.push({Time:time,League:f.league,Home:f.homeTeam,Away:f.awayTeam,EventID:f.eventId,MarketID:m.id,Market:m.name,Specifier:m.specifier,Selection:o.name,OutcomeID:o.id,Odds:o.odds,Active:o.active?"Yes":"No"});}
 const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"All Markets");
 XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(fixtures.map(f=>({Time:new Intl.DateTimeFormat("en-GB",{timeZone:timezone,dateStyle:"short",timeStyle:"short",hour12:false}).format(new Date(f.startMs)),League:f.league,Home:f.homeTeam,Away:f.awayTeam,EventID:f.eventId,Markets:f.markets.length}))),"Games");
 return XLSX.write(wb,{type:"buffer",bookType:"xlsx"});
}
export function makePdf(fixtures,timezone,title){return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:"A4",margin:36}),chunks=[];doc.on("data",c=>chunks.push(c));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);
 doc.fontSize(18).text(title,{align:"center"}); doc.moveDown(.4); doc.fontSize(8).text(`Generated ${new Intl.DateTimeFormat("en-GB",{timeZone:timezone,dateStyle:"medium",timeStyle:"short"}).format(new Date())} • SportyBet Nigeria`,{align:"center"}); doc.moveDown();
 for(const f of fixtures){if(doc.y>700)doc.addPage(); const time=new Intl.DateTimeFormat("en-GB",{timeZone:timezone,dateStyle:"short",timeStyle:"short",hour12:false}).format(new Date(f.startMs)); doc.fontSize(11).font("Helvetica-Bold").text(`${time} | ${f.league}`); doc.font("Helvetica").fontSize(10).text(`${f.homeTeam} vs ${f.awayTeam}`); doc.fontSize(7).text(`Event: ${f.eventId}`); for(const m of f.markets){if(doc.y>735)doc.addPage(); doc.moveDown(.2);doc.fontSize(8).font("Helvetica-Bold").text(`${m.name}${m.specifier?` (${m.specifier})`:""}`);doc.font("Helvetica").fontSize(7).text(m.outcomes.map(o=>`${o.name}: ${Number.isFinite(o.odds)?o.odds.toFixed(2):"—"}`).join(" • ")||"No outcomes");} doc.moveDown(.5);doc.moveTo(36,doc.y).lineTo(559,doc.y).stroke();doc.moveDown(.5);}
 if(!fixtures.length)doc.fontSize(11).text("No fixtures found for the selected date.");doc.fontSize(7).text("Odds can change. This bot retrieves data and generates reports; it does not place wagers.",36,790,{width:523,align:"center"});doc.end();});}