import {getFixtures,filterByDay} from "../lib/sportybet.js";
import {makePdf,makeXlsx} from "../lib/reports.js";
const TOKEN=process.env.TELEGRAM_BOT_TOKEN, SECRET=process.env.BOT_SECRET, TZ=process.env.REPORT_TIMEZONE||"Africa/Lagos";
async function tg(method,body){return fetch(`https://api.telegram.org/bot${TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});}
async function sendText(chatId,text){return tg("sendMessage",{chat_id:chatId,text});}
async function sendDocument(chatId,buffer,filename,caption){const form=new FormData();form.append("chat_id",String(chatId));form.append("caption",caption);form.append("document",new Blob([buffer]),filename);return fetch(`https://api.telegram.org/bot${TOKEN}/sendDocument`,{method:"POST",body:form});}
export default async function handler(req,res){if(req.method!=="POST")return res.status(200).json({ok:true});if(SECRET&&req.headers["x-telegram-bot-api-secret-token"]!==SECRET)return res.status(401).end();try{const msg=req.body?.message;if(!msg?.chat?.id)return res.status(200).json({ok:true});const chatId=msg.chat.id,text=(msg.text||"").trim().toLowerCase();
 if(text==="/start"||text==="/help")return await sendText(chatId,"⚽ SportyBet Markets Bot\n\n/today — today's games\n/tomorrow — tomorrow's games\n/pdf — today's PDF\n/pdf_tomorrow — tomorrow's PDF\n/excel — today's spreadsheet\n/excel_tomorrow — tomorrow's spreadsheet\n\nThe bot retrieves SportyBet data and does not place wagers."),res.status(200).json({ok:true});
 const valid=["/today","/tomorrow","/pdf","/pdf_tomorrow","/excel","/excel_tomorrow"];if(!valid.includes(text))return await sendText(chatId,"Use /today, /tomorrow, /pdf, or /excel. Send /help for all commands."),res.status(200).json({ok:true});
 const offset=text.includes("tomorrow")?1:0,isExcel=text.startsWith("/excel"),isPdf=text.startsWith("/pdf");await sendText(chatId,`⏳ Fetching SportyBet fixtures and markets for ${offset?"tomorrow":"today"}...`);const raw=await getFixtures({hours:offset?72:48});const fixtures=filterByDay(raw,offset,TZ);
 if(text==="/today"||text==="/tomorrow")return await sendText(chatId,`⚽ ${offset?"Tomorrow":"Today"}\n\nGames: ${fixtures.length}\nMarket groups: ${fixtures.reduce((n,f)=>n+f.markets.length,0)}\n\nUse /pdf or /excel to download the full report.`),res.status(200).json({ok:true});
 if(isPdf){const b=await makePdf(fixtures,TZ,`SportyBet Football Markets — ${offset?"Tomorrow":"Today"}`);await sendDocument(chatId,b,`sportybet-${offset?"tomorrow":"today"}.pdf`,`📄 SportyBet report • ${fixtures.length} games`);}else{const b=makeXlsx(fixtures,TZ);await sendDocument(chatId,b,`sportybet-${offset?"tomorrow":"today"}.xlsx`,`📊 SportyBet spreadsheet • ${fixtures.length} games`);}return res.status(200).json({ok:true});
 }catch(e){console.error(e);if(req.body?.message?.chat?.id)await sendText(req.body.message.chat.id,`❌ Error: ${e.message||"Unable to retrieve SportyBet data."}`);return res.status(200).json({ok:false});}}
